In [2]:
import torch
import torch.nn as nn


In [5]:
inputs = torch.Tensor([[[0.2, 0.1, 0.3], [0.5, 0.1, 0.1]]])
B, S, E = inputs.size()
inputs = inputs.reshape(S, B, E)

In [13]:
means=inputs.mean(dim=-1,keepdim=True)
print(means)
means.shape

tensor([[[0.2000]],

        [[0.2333]]])


torch.Size([2, 1, 1])

In [19]:
variance=((inputs-means)**2).mean(dim=-1,keepdim=True)
eps=1e-5
std=(variance+eps).sqrt()

In [20]:
(inputs-means)/std

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]])

In [24]:
parameter_shape = inputs.size()[-2:]
gamma = nn.Parameter(torch.ones(parameter_shape))
beta =  nn.Parameter(torch.zeros(parameter_shape))

In [27]:
beta

Parameter containing:
tensor([[0., 0., 0.]], requires_grad=True)

In [28]:
gamma*(inputs-means)/std+beta

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)

In [ ]:
class LayerNorm(nn.Module):
    def __init__(self, emb_dim):
        super().__init__()
        self.eps = 1e-5
        self.scale = nn.Parameter(torch.ones(emb_dim))
        self.shift = nn.Parameter(torch.zeros(emb_dim))

    def forward(self, x):
        mean = x.mean(dim=-1, keepdim=True)
        var = x.var(dim=-1, keepdim=True, unbiased=False)
        norm_x = (x - mean) / torch.sqrt(var + self.eps)

        return self.scale * norm_x + self.shift
# Sample Input
inputs = torch.tensor([
    [0.43, 0.15, 0.89],  
    [0.55, 0.87, 0.66],  
    [0.57, 0.85, 0.64],  
    [0.22, 0.58, 0.33],  
    [0.77, 0.25, 0.10],  
    [0.05, 0.80, 0.55]   
])

batch = torch.stack((inputs, inputs), dim=0)  
ln=LayerNorm(emb_dim=3)
ln(batch)

torch.Size([2, 6, 3])



tensor([[[-0.1967, -1.1144,  1.3111],
         [-1.0794,  1.3305, -0.2510],
         [-0.9802,  1.3723, -0.3921],
         [-1.0399,  1.3496, -0.3097],
         [ 1.3816, -0.4296, -0.9520],
         [-1.3362,  1.0690,  0.2672]],

        [[-0.1967, -1.1144,  1.3111],
         [-1.0794,  1.3305, -0.2510],
         [-0.9802,  1.3723, -0.3921],
         [-1.0399,  1.3496, -0.3097],
         [ 1.3816, -0.4296, -0.9520],
         [-1.3362,  1.0690,  0.2672]]], grad_fn=<AddBackward0>)